### ISSUE TITLE
Please explain database and cache use

### ISSUE THREAD

**Issue by bluepuma77** [italia/verificac19-sdk#26]
Please explain database and cache use. Even though the database is not connected, I can still fully check signature, rules and validation (with existing cache files). Just `Service.updateAll()` is not working. What is the database used for?

Furthermore `Service.updateAll()` is rejecting a promise if the database is not reachable, which is killing the whole process, can't even try/catch. That could be classified as a bug.

```
$ docker run -it -v $(pwd):/app --env VC19_CACHE_FOLDER=./cache -w /app node:16-alpine node alone.js
Certificate: {
  person: {
    standardisedFamilyName: 'X',
    familyName: 'X',
    standardisedGivenName: 'Y',
    givenName: 'Y'
  },
  dateOfBirth: '1900-01-01',
  vaccinations: [
    {
      disease: '840539006',
      vaccine: 'J07BX03',
      medicinalProduct: 'EU/1/20/1528',
      manufacturer: 'ORG-100030215',
      doseNumber: 2,
      totalSeriesOfDoses: 2,
      dateOfVaccination: '2021-10-01',
      countryOfVaccination: 'FR',
      certificateIssuer: 'CNAM',
      certificateIdentifier: 'URN:UVCI:01:FR:T5DWTJYS4XYZ#4'
    }
  ],
  tests: undefined,
  recoveryStatements: undefined,
  kid: '53FOjX/4XYZ='
}

Signature: true

Rules: { result: false, code: 'REVOKED', message: 'UVCI is in blacklist' }

Validation: {
  person: 'X Y',
  date_of_birth: '1900-01-01',
  result: false,
  code: 'REVOKED',
  message: 'UVCI is in blacklist'
}

Starting update...
TEST: Can not connect to MongoDB

<now it takes some time before killing the whole process>

REJECTION: MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at NativeConnection.Connection.openUri (/app/node_modules/mongoose/lib/connection.js:801:32)
    at Mongoose.createConnection (/app/node_modules/mongoose/lib/index.js:285:10)
    at CRL.setUp (/app/node_modules/verificac19-sdk/src/crl.js:7:41)
    at Cache.setUp (/app/node_modules/verificac19-sdk/src/cache.js:34:30)
    at setUp (/app/node_modules/verificac19-sdk/src/service.js:7:15)
    at Object.updateAll (/app/node_modules/verificac19-sdk/src/service.js:109:9)
    at main (/app/alone.js:28:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

```
// alone.js
const { MongoClient } = require('mongodb');
const { Certificate, Service, Validator } = require('verificac19-sdk')

let mongo_default = 'mongodb://root:example@localhost:27017/VC19?authSource=admin'
let cert = 'HC1:A1B2C3D4E5...';

process.on('SIGINT', function () { process.exit() });
process.on('SIGTERM', function () { process.exit() });
process.on('unhandledRejection', (reason, promise) => {
    console.log('REJECTION:', reason.stack || reason)
});

const main = async () => {
    certificate = await Certificate.fromRaw(cert);
    console.log('Certificate:', certificate, '\n')

    signature = await Validator.checkSignature(certificate);
    console.log('Signature':, signature, '\n');

    rules = await Validator.checkRules(certificate);
    console.log('Rules:', rules, '\n');

    validation = await Validator.validate(certificate)
    console.log('Validation:', validation, '\n');

    console.log('Starting update...');
    try {
        await Service.updateAll();
    } catch (err) {
        // THIS IS NEVER REACHED
        console.log('ERROR:', err)
    }
    console.log('...finished update');
}

// check ourself if the database is reachable
MongoClient.connect(process.env.VC19_MONGODB_URL || mongo_default, {
    connectTimeoutMS: 1000,
    serverSelectionTimeoutMS: 1000,
}, function (err, db) {
    if (err) {
        console.log('TEST: Can not connect to MongoDB')
    } else {
        console.log('TEST: Connected to MongoDB')
        db.close();
    }
});

main();
```

**Comment by bluepuma77** [comment]
And even if the database is successfully connected and `Service.updateAll()` finishes successfully, I still get an error for every call to `Validator.validate(certificate)` (but that call is still successfully executed):

```
2022-01-27T22:52:19.867096170Z REJECTION: MongoNotConnectedError: MongoClient must be connected to perform this operation
2022-01-27T22:52:19.867265778Z     at getTopology (/home/node/app/node_modules/mongodb/lib/utils.js:367:11)
2022-01-27T22:52:19.867661476Z     at Collection.find (/home/node/app/node_modules/mongodb/lib/collection.js:243:69)
2022-01-27T22:52:19.867698353Z     at Collection.findOne (/home/node/app/node_modules/mongodb/lib/collection.js:234:21)
2022-01-27T22:52:19.867784987Z     at NativeCollection.<computed> [as findOne] (/home/node/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:199:33)
2022-01-27T22:52:19.867824797Z     at NativeCollection.Collection.doQueue (/home/node/app/node_modules/mongoose/lib/collection.js:135:23)
2022-01-27T22:52:19.867969289Z     at /home/node/app/node_modules/mongoose/lib/collection.js:82:24
2022-01-27T22:52:19.867997496Z     at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**Comment by astagi** [comment]
Hi @bluepuma77 

MongoDB is used to store Certificates revocation list (CRL), cache files are used to store DSC and settings. 

In the second example I see you get a rejection if MongoDB is not connected, that’s right, you need to compare your DGC with CRL and MongoDB must be connected.

[Here](https://github.com/italia/verificac19-sdk/blob/57294bad674c45d028205944ee40fdaeccb1998b/src/validator.js#L401) you can see SDK checking wether cache is ready or not.

If you have any idea to improve CRL code, please let me know :)

**Comment by bluepuma77** [comment]
Hi @astagi, sorry, it's still not clear to me. 

You write that the Certificates revocation list (CRL) is stored in MongoDB. 

But I get this without a MongoDB connection:

```
Validation: {
  person: 'X Y',
  date_of_birth: '1900-01-01',
  result: false,
  code: 'REVOKED',
  message: 'UVCI is in blacklist'
}
```

I would expect that the CRL is responsible for being able to revoke a certificate?

**Comment by bluepuma77** [comment]
Two more questions:

1. Where is the end date of `Validator.validate(certificate)` coming from?
```
"validation": {
    "person": "A B",
    "date_of_birth": "1977-01-01",
    "result": true,
    "code": "VALID",
    "message": "Doses 3/3 - Vaccination is valid [ 2021-12-15T00:00:00.000Z - 2022-09-11T00:00:00.000Z ] "
  }
```
 (And why is it not available in an easier machine-readable attribute ;-)

2. And what about the rules? For most of my tested certificates the return of `Validator.checkRules(certificate)` is empty.

**Comment by astagi** [comment]
> Hi @astagi, sorry, it's still not clear to me.
> 
> You write that the Certificates revocation list (CRL) is stored in MongoDB.
> 
> But I get this without a MongoDB connection:
> 
> ```
> Validation: {
>   person: 'X Y',
>   date_of_birth: '1900-01-01',
>   result: false,
>   code: 'REVOKED',
>   message: 'UVCI is in blacklist'
> }
> ```
> 
> I would expect that the CRL is responsible for being able to revoke a certificate?

There are two places where you can get revoke certificates:

1. CRL stored in MongoDB
2. UVCI blacklist in settings [here](https://get.dgc.gov.it/v1/dgc/settings)

I know it might appear confusing but the UVCI blacklist in settings was made before CRL backend implementation, at the moment we need to keep these two systems to have a complete list of revoked certificates.

Maybe an error would be better in case of missing connection, let me investigate!

**Comment by bluepuma77** [comment]
Closing for now
