### ISSUE TITLE
ReferenceError: TextDecoder is not defined

### ISSUE THREAD

**Issue by gmm9200** [italia/verificac19-sdk#9]
Salve a tutti, sono alle prime armi con NodeJs e cercando di seguire la documentazione passo ho provato ad eseguire i file contenuti nella cartella examples dopo aver clonato il repository e installato le dipendenze. 

Quando do il comando
`node syncdata.js`

il processo riscontra il seguente errore: 
`ReferenceError: TextDecoder is not defined
    at Object.202 (/root/test_sdk_verificac19/verificac19-sdk-master/node_modules/cbor-web/dist/cbor.js:2:59224)
    at r (/root/test_sdk_verificac19/verificac19-sdk-master/node_modules/cbor-web/dist/cbor.js:2:114825)
    at Object.873 (/root/test_sdk_verificac19/verificac19-sdk-master/node_modules/cbor-web/dist/cbor.js:2:55961)
    at r (/root/test_sdk_verificac19/verificac19-sdk-master/node_modules/cbor-web/dist/cbor.js:2:114825)
    at Object.20 (/root/test_sdk_verificac19/verificac19-sdk-master/node_modules/cbor-web/dist/cbor.js:2:27297)
    at r (/root/test_sdk_verificac19/verificac19-sdk-master/node_modules/cbor-web/dist/cbor.js:2:114825)
    at Object.141 (/root/test_sdk_verificac19/verificac19-sdk-master/node_modules/cbor-web/dist/cbor.js:2:26717)
    at r (/root/test_sdk_verificac19/verificac19-sdk-master/node_modules/cbor-web/dist/cbor.js:2:114825)
    at /root/test_sdk_verificac19/verificac19-sdk-master/node_modules/cbor-web/dist/cbor.js:2:115792
    at /root/test_sdk_verificac19/verificac19-sdk-master/node_modules/cbor-web/dist/cbor.js:2:115800
`

Ottengo un errore molto simile con "ReferenceError: TextDecoder is not defined" se provo a lanciare
`npm run test`

Qualcuno può aiutarmi?

**Comment by astagi** [comment]
Ciao @gmm9200 

che sistema operativo stai usando? e quale versione di node?

**Comment by gmm9200** [comment]
Ciao @astagi grazie per la risposta celere

Nodejs v10.19.0
Ubuntu 20.04.3

**Comment by astagi** [comment]
Ah ok @gmm9200, prova ad aggiornare Nodejs alla versione 12.x almeno, la 10.x non è più supportata.

Fammi sapere se funziona!

**Comment by dcannova** [comment]
Confermo, avevo avuto lo stesso problema anche io, metti node 14.

**Comment by gmm9200** [comment]
Risolto, grazie per la dritta!

Effettivamente nei repo di Ubuntu c'è una versione piuttosto datata il cui supporto è scaduto quest'anno.

Per chi usa Ubuntu conviene scaricarsi una versione più aggiornata con snap or PPA

Nel mio caso è bastato lanciare questo comando
`sudo snap install node`

**Comment by astagi** [comment]
Ottimo @gmm9200 grazie anche a @dcannova per il feedback!
